# Singular Value Decomposition (SVD)

What is SVD? 
-> SVD is an matrix decomposition method for reducing a matrix into its consituent part so that subsequent matrix calculations are simpler. 
note: valid for only real numbers. 

In [7]:
import numpy as np 
from scipy.linalg import svd

A = U.Sigma.V^T

A is a matrix of m x n

U,V^T are orthonormal vectors (mxr and rxn) respectively


In [4]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

In [37]:
A


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
%time U, S, VT = svd(A)

Wall time: 0 ns


In [11]:
U.shape,S.shape,VT.shape

((4, 4), (2,), (2, 2))

In [21]:
print(U)

[[-0.15248323 -0.82264747 -0.39450102 -0.37995913]
 [-0.34991837 -0.42137529  0.24279655  0.80065588]
 [-0.54735351 -0.0201031   0.69790998 -0.46143436]
 [-0.74478865  0.38116908 -0.5462055   0.04073761]]


In [19]:
print(S)

[14.2690955   0.62682823]


In [20]:
print(VT)

[[-0.64142303 -0.7671874 ]
 [ 0.7671874  -0.64142303]]


reconstructing the SVD and getting back the original matrix A 

In [23]:
# reason we for double parenthesis is because function expects a tuple.
sigma = np.zeros((A.shape[0],A.shape[1])) 

In [24]:
sigma

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
# setting the diagonal of the zero matrix with our sigma vector obtained from svd
# this step is required only when original matrix is m x n. if original matrix is m x m.
# diag can be applied directly to sigma. 
sigma[:A.shape[1],:A.shape[1]] = np.diag(S)

In [35]:
# taking the dot product 
B = U.dot(sigma.dot(VT))

In [42]:
B

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

Applications of SVD
1) data compression 
2) netflix recommendation systems
3) NLP
... 